---
 
- hosts: all
  become: true
  pre_tasks:
 
  - name: install updates for Debian
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install updates for CentOS
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- import_playbook: install_apache.yml
- import_playbook: install_mysql.yml
